#服务端口号 8010
server:
  port: 8010
spring:
  #服务名称
  application:
    name: order-service
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-order?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #nacos配置信息
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
# seata 配置
seata:
  tx-service-group: my_group
  service:
    vgroup-mapping:
      my_group: seata-server
    grouplist:
      seata-server: localhost:8091
  enabled: true
#日志级别、格式
logging:
  level:
    cn.nean: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS